// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBexample-your-android-api-key',
    appId: '1:359427579558:android:example-app-id',
    messagingSenderId: '359427579558',
    projectId: 'taya-backend-b8316',
    storageBucket: 'taya-backend-b8316.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBexample-your-ios-api-key',
    appId: '1:359427579558:ios:example-ios-app-id',
    messagingSenderId: '359427579558',
    projectId: 'taya-backend-b8316',
    storageBucket: 'taya-backend-b8316.firebasestorage.app',
    androidClientId: '359427579558-example-android-client.apps.googleusercontent.com',
    iosClientId: '359427579558-ohcrhfuq1t9iiqrt8p2p4mfljbao1oqp.apps.googleusercontent.com',
    iosBundleId: 'com.tayaapp.yourapp.dev',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBexample-your-web-api-key',
    appId: '1:359427579558:web:example-web-app-id',
    messagingSenderId: '359427579558',
    projectId: 'taya-backend-b8316',
    authDomain: 'taya-backend-b8316.firebaseapp.com',
    storageBucket: 'taya-backend-b8316.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBexample-your-macos-api-key',
    appId: '1:359427579558:ios:example-macos-app-id',
    messagingSenderId: '359427579558',
    projectId: 'taya-backend-b8316',
    storageBucket: 'taya-backend-b8316.firebasestorage.app',
    androidClientId: '359427579558-example-android-client.apps.googleusercontent.com',
    iosClientId: '359427579558-ohcrhfuq1t9iiqrt8p2p4mfljbao1oqp.apps.googleusercontent.com',
    iosBundleId: 'com.tayaapp.yourapp.dev',
  );
}
